spring:
  datasource:
    platform: postgres
    password: "resist2024"
    url: "jdbc:postgresql://communalist-dev-db.c6s7i98evzpt.us-west-1.rds.amazonaws.com:5432/"
    username: "postgres"

server:
  port: 8082